---
title: "HW2"
author: Yue Yin
date: September 27, 2021
output: github_document
---

```{r}
library(dplyr)
library(nycflights13)
library(ggplot2)
library(lubridate)
```

```{r}
#1
summary(flights)
```

8255 flights have missing `dep_time`. Other variables that are missing `dep_delay`, `arr_time`, `arr_delay` and `air_time`. These rows may represent flights that failed to depart or arrive. They may also be incomplete because the data was lost.

```{r}
#2
flights %>% 
  mutate(dep_time = dep_time %/% 100 * 60 + dep_time %% 100,
         sched_dep_time = sched_dep_time %/% 100 * 60 + sched_dep_time %% 100)
```

```{r}
#3
flights %>% 
  mutate(dep_day = make_date(year, month, day)) %>% 
  group_by(dep_day) %>% 
  summarize(canceled = sum(is.na(dep_time)),
            count = n(),
            canceled_prop = canceled/count,
            mean_dep_delay = mean(dep_delay, na.rm = T),
            mean_arr_delay = mean(arr_delay, na.rm = T)) %>%
  ggplot(aes(x= canceled_prop)) + 
  geom_point(aes(y=mean_dep_delay), color = 'purple') +
  geom_point(aes(y=mean_arr_delay), color = 'blue')
```




